# Generated by Django 2.1.7 on 2019-03-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190322_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_tweets',
            field=models.IntegerField(default=0),
        ),
    ]
