# Generated by Django 2.1.7 on 2019-03-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190323_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
