# Generated by Django 2.1.7 on 2019-03-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hashtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Hi! This is my twitter!'),
        ),
    ]
