# Generated by Django 2.1.7 on 2019-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='https://bulma.io/images/placeholders/128x128.png', max_length=200),
        ),
    ]
