# Generated by Django 2.1.7 on 2019-03-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='replies',
            field=models.ManyToManyField(related_name='replies', to='core.Reply'),
        ),
    ]
