# Generated by Django 2.1.7 on 2019-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='https://unpkg.com/bulmaswatch/darkly/bulmaswatch.min.css', max_length=200),
        ),
    ]
